CREATE TABLE orders
(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT,
total_price DECIMAL(10,2) NOT NULL,
status ENUM(PENDING,, PROCESSING’, ‘SHIPPED’, ‘DELIVERED’, CANCELLED’)
DEFAULT PENDING,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id)
);