CREATE TABLE payments
(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_id BIGINT,
order_id BIGINT,
amount DECIMAL(10,2) NOT NULL,
status ENUM(SUCCESS:, ‘FAILED’, PENDING’) DEFAULT ‘PENDING’,
transaction_id VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (order_id) REFERENCES orders(id)
);